title: Actuarial notation with <span class="latex">L<sup>a</sup>T<sub>e</sub>X</span>
description: Typesetting actuarial symbols easily and consistently
theme: jekyll-theme-cayman
show_downloads: "false"
